language: node_js
node_js:
- node
deploy:
  provider: npm
  email: pkrawz@gmail.com
  on:
    tags: true
    repo: pkrawc/thermal-ui
  api_key:
    secure: jaNbGta2Y/M3CWEHtr2IT9Xu8vmn8n1k/QS6oyBPt9y+/qA0RXDXYS6drGSPV4kv/hoCIRUfEXxzLKRB0poR+2qRxqi8QbTwucZFRHUBuqoGG155I0KfsRXlmfdM+OJpzLNoQj60H7EOA2iuqDmIOLqHNd+r8FzPjXmPi2XZGxFJ59RbjSSQq80sCs0/gw1ePQS5O/+AYOKM1zrlgehTIBQUxtyKenzjQwe3u4+TnVPaI2Nan+BVbHDrD+Ug/NwRwcmivwdRGKcg/9Kiph9Us8iKeiAYQKAZstL9kLHFS3NXDIRPps7uXJrZU4BA1N9jCh+vCxlGndkwhU7/PSoyvwd1QSSbzo+wndSZ53MaPAADbAgpZnoc0q97Sx2QF0uWfUxLLgWtReRAFYwoBw775HJoim8m4IwyRABMYd2yaCHZPp3pViv+jLc8gOaizcGRrDrtUzpm1MezwRWSCW51pfjGg4lbmV0OV8KpVxzhOLb4bsdTK+Q6s5Gp4++xbMqf66dPJdhav13Lld0tj9XjPYHgHzhnrsJRZG4cmJ48K+XP4d8SAJASnQmzlLfyTEOicVg4PvzkzjooRhL3Vl5q/JCJZKM+xqcgP+AgtQh6SpL00I5t96X85LVbn/PO+kIXGe1A4X88u+HG/IurU1L6k3Cq3BtRjuBMVt8vyomp7zw=
notifications:
  email:
  - pkrawz@gmail.com
